# Generated by Django 5.2.15 on 2026-06-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_city_hotel_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='available_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='available_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
