# Generated by Django 5.2.15 on 2026-06-09 17:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room_available_from_room_available_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
