# Generated by Django 5.2.15 on 2026-06-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_city_description_city_lat_city_lon_cityimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='location',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
